name: "Test coverage comment"
description: "Leave a test coverage comment on pull request."
author: "pooi (Taewoo You) / modified by kimohy (Moohyun Kim)"

inputs:
  github-token:
    description: "secrets.GITHUB_TOKEN value"
    required: true
  xml-test-report-path:
    description: 'The test report paths (xml, split by comma(,))'
    required: true

runs:
  using: composite
  steps:
    - run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash
    - name: Extract test coverage
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/main.py "${{ inputs.xml-test-report-path }}" ${{ inputs.github-token }} ${{ github.api_url }} ${{ github.repository }} ${{ github.ref }} ${{ github.event.pull_request.url }}
